<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_error_box</name>
   <tag></tag>
   <elementGuidId>124c1bea-ecca-435a-8162-239b117f28a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[count(. | //*[@class = 'pam login_error_box uiBoxRed']) = count(//*[@class = 'pam login_error_box uiBoxRed'])][count(. | //*[@role = 'alert']) = count(//*[@role = 'alert'])][count(. | //*[@tabindex = '0']) = count(//*[@tabindex = '0'])][count(. | //*[@id = 'error_box']) = count(//*[@id = 'error_box'])][count(. | id(&quot;error_box&quot;)) = count(id(&quot;error_box&quot;))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;error_box&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pam login_error_box uiBoxRed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error_box</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error_box&quot;)</value>
   </webElementProperties>
</WebElementEntity>
