<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_renewpassword</name>
   <tag></tag>
   <elementGuidId>af317936-e637-4707-951c-4e4fe4967102</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dot6ul-3 hrTYle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renewpassword</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{8,}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 jxXbOM&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/div[@class=&quot;cmag0j-1-sc-gipzik dkuDum&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-kAzzGY JbQyp e9phw6-0 gUkenf&quot;]/div[1]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 bScUdW&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/form[@class=&quot;lzru6b-0 dcOwwC&quot;]/div[3]/div[@class=&quot;dot6ul-0 KrcEX&quot;]/div[@class=&quot;dot6ul-1 cVPFlx&quot;]/input[@class=&quot;dot6ul-3 hrTYle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
