<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>c7abb103-e965-4266-9f11-720b6c0f68f8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dot6ul-3 hrTYle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kevin.ang@oddle.me</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 nuiWo&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/div[@class=&quot;cmag0j-1-sc-gipzik dkuDum&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-kAzzGY JbQyp e9phw6-0 gUkenf&quot;]/div[1]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 iNeBZk&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/form[@class=&quot;lzru6b-0 dcOwwC&quot;]/div[1]/div[@class=&quot;dot6ul-0 hXxpax&quot;]/div[@class=&quot;dot6ul-1 cVPFlx&quot;]/input[@class=&quot;dot6ul-3 hrTYle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
