<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_delete address</name>
   <tag></tag>
   <elementGuidId>441ba4ad-eefe-4d61-a27f-a5034421813f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//svg[count(. | id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 cNgNgb&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/div[@class=&quot;cmag0j-1-sc-gipzik dkuDum&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[1]/div[@class=&quot;e9phw6-1-sc-kAzzGY JbQyp e9phw6-0 gUkenf&quot;]/div[1]/div[@class=&quot;s85dwy8-0 kqgYzi&quot;]/div[@class=&quot;s85dwy8-1 iLFtXI e9phw6-0 jBJmyp&quot;]/div[@class=&quot;s19enx61-0 eexayc e9phw6-1-sc-bdVaJa QPZnU e9phw6-0 jBJmyp&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/button[@class=&quot;cb1xkz-0 jrtCvp&quot;]/svg[1]) = count(id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 cNgNgb&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/div[@class=&quot;cmag0j-1-sc-gipzik dkuDum&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[1]/div[@class=&quot;e9phw6-1-sc-kAzzGY JbQyp e9phw6-0 gUkenf&quot;]/div[1]/div[@class=&quot;s85dwy8-0 kqgYzi&quot;]/div[@class=&quot;s85dwy8-1 iLFtXI e9phw6-0 jBJmyp&quot;]/div[@class=&quot;s19enx61-0 eexayc e9phw6-1-sc-bdVaJa QPZnU e9phw6-0 jBJmyp&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/button[@class=&quot;cb1xkz-0 jrtCvp&quot;]/svg[1])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/div[1]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/button/svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 15 15</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 cNgNgb&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/div[@class=&quot;cmag0j-1-sc-gipzik dkuDum&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[1]/div[@class=&quot;e9phw6-1-sc-kAzzGY JbQyp e9phw6-0 gUkenf&quot;]/div[1]/div[@class=&quot;s85dwy8-0 kqgYzi&quot;]/div[@class=&quot;s85dwy8-1 iLFtXI e9phw6-0 jBJmyp&quot;]/div[@class=&quot;s19enx61-0 eexayc e9phw6-1-sc-bdVaJa QPZnU e9phw6-0 jBJmyp&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/button[@class=&quot;cb1xkz-0 jrtCvp&quot;]/svg[1]</value>
   </webElementProperties>
</WebElementEntity>
