<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>e646c741-6b49-42f9-bd25-5c6bd8168f2b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s1nouw8s-2 gsOhjW</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en_SG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/div[@class=&quot;s1ikpaay-0 hnXEWZ&quot;]/div[@class=&quot;s1ikpaay-1 ebgyAt&quot;]/div[@class=&quot;b95ya3-0 lopHMx e9phw6-1-sc-bdVaJa jUFEmu e9phw6-0 jBJmyp&quot;]/div[@class=&quot;s1ikpaay-4 drrHoE&quot;]/div[@class=&quot;s19enx61-0 eexayc e9phw6-1-sc-bdVaJa QPZnU e9phw6-0 jBJmyp&quot;]/div[@class=&quot;s19enx61-3-sc-jlyJG hNZsXk e9phw6-1-sc-bdVaJa gamxMN e9phw6-0 jBJmyp&quot;]/div[@class=&quot;e2lxka-3 idLvhV&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa iriZUy e9phw6-0 jBJmyp&quot;]/a[@class=&quot;s1nouw8s-2 gsOhjW&quot;]</value>
   </webElementProperties>
</WebElementEntity>
