<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_promo2</name>
   <tag></tag>
   <elementGuidId>8f3e1d12-1a89-4765-a41b-88e0995d4e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = '/en_SG/promotion/1']) = count(//*[@href = '/en_SG/promotion/1'])][count(. | id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 jxXbOM&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;s1mv1owp-2 fAMmCH&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-frame&quot;]/ul[@class=&quot;slider-list&quot;]/li[@class=&quot;slider-slide&quot;]/div[@class=&quot;s1mv1owp-3 WNftd&quot;]/div[@class=&quot;s1mv1owp-4 ekpiGH&quot;]/a[1]) = count(id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 jxXbOM&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;s1mv1owp-2 fAMmCH&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-frame&quot;]/ul[@class=&quot;slider-list&quot;]/li[@class=&quot;slider-slide&quot;]/div[@class=&quot;s1mv1owp-3 WNftd&quot;]/div[@class=&quot;s1mv1owp-4 ekpiGH&quot;]/a[1])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/div[1]/div[2]/div/div/div[2]/div[1]/ul/li[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en_SG/promotion/1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;s134bqp5-1 jxXbOM&quot;]/div[@class=&quot;m7p8f0-0 fUTidt&quot;]/div[@class=&quot;s1ikpaay-4 dAQshL&quot;]/div[@class=&quot;s1mv1owp-2 fAMmCH&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-frame&quot;]/ul[@class=&quot;slider-list&quot;]/li[@class=&quot;slider-slide&quot;]/div[@class=&quot;s1mv1owp-3 WNftd&quot;]/div[@class=&quot;s1mv1owp-4 ekpiGH&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
