<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_promonext-XPATH</name>
   <tag></tag>
   <elementGuidId>0c36590c-8a3e-4ed7-b960-25abe8af716d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;body&quot;]/div[1]/div[2]/div/div/div[2]/div[3]/button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/div[1]/div[2]/div/div/div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s1mv1owp-8 waUbW cb1xkz-0 jrtCvp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;body&quot;]/div[1]/div[2]/div/div/div[2]/div[3]/button</value>
   </webElementProperties>
</WebElementEntity>
