<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_storename-XPATH</name>
   <tag></tag>
   <elementGuidId>e675bb02-4524-42f3-b29e-50f0e065c3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/div/div/div/div[2]/div[1]/div[1]/div/div/div/div[1]/div[2]/a/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e9phw6-1-sc-bdVaJa bYlqBK e9phw6-0 jaALZg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/div/div/div/div[2]/div[1]/div[1]/div/div/div/div[1]/div[2]/a/div/h1</value>
   </webElementProperties>
</WebElementEntity>
