<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>7c0dbef0-a800-405c-8477-37bdf05fb7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[count(. | //*[@class = 's3mrp9-0 dWBhZP']) = count(//*[@class = 's3mrp9-0 dWBhZP'])][count(. | //*[text() = 'Login']) = count(//*[text() = 'Login'])][count(. | id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[3]/div[3]/div[@class=&quot;wuzp1o-0 cCUvkJ&quot;]/div[@class=&quot;wuzp1o-2 gfSaCZ&quot;]/div[@class=&quot;wuzp1o-5 eezkNJ&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 kImoTU&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/div[@class=&quot;qxyyek-0 gDhhcJ e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/div[@class=&quot;sc-Rmtcm lkffjx e9phw6-0 jBJmyp&quot;]/form[1]/button[@class=&quot;s3mrp9-0 dWBhZP&quot;]) = count(id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[3]/div[3]/div[@class=&quot;wuzp1o-0 cCUvkJ&quot;]/div[@class=&quot;wuzp1o-2 gfSaCZ&quot;]/div[@class=&quot;wuzp1o-5 eezkNJ&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 kImoTU&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/div[@class=&quot;qxyyek-0 gDhhcJ e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/div[@class=&quot;sc-Rmtcm lkffjx e9phw6-0 jBJmyp&quot;]/form[1]/button[@class=&quot;s3mrp9-0 dWBhZP&quot;])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/div/div/div[3]/div[3]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s3mrp9-0 dWBhZP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[3]/div[3]/div[@class=&quot;wuzp1o-0 cCUvkJ&quot;]/div[@class=&quot;wuzp1o-2 gfSaCZ&quot;]/div[@class=&quot;wuzp1o-5 eezkNJ&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 kImoTU&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/div[@class=&quot;qxyyek-0 gDhhcJ e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/div[@class=&quot;sc-Rmtcm lkffjx e9phw6-0 jBJmyp&quot;]/form[1]/button[@class=&quot;s3mrp9-0 dWBhZP&quot;]</value>
   </webElementProperties>
</WebElementEntity>
