<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_login_fbpage</name>
   <tag></tag>
   <elementGuidId>570fc2a0-0088-4def-8862-a2af62d03c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@value = 'Log In']) = count(//*[@value = 'Log In'])][count(. | //*[@tabindex = '4']) = count(//*[@tabindex = '4'])][count(. | //*[@data-testid = 'royal_login_button']) = count(//*[@data-testid = 'royal_login_button'])][count(. | //*[@type = 'submit']) = count(//*[@type = 'submit'])][count(. | //*[@id = 'u_0_2']) = count(//*[@id = 'u_0_2'])][count(. | id(&quot;u_0_2&quot;)) = count(id(&quot;u_0_2&quot;))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;loginbutton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>royal_login_button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_2&quot;)</value>
   </webElementProperties>
</WebElementEntity>
