<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_loginbutton</name>
   <tag></tag>
   <elementGuidId>651505a2-255a-4a5d-9edd-e59a0e044111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[count(. | //*[@class = 'uiButton uiButtonConfirm uiButtonLarge']) = count(//*[@class = 'uiButton uiButtonConfirm uiButtonLarge'])][count(. | //*[@id = 'loginbutton']) = count(//*[@id = 'loginbutton'])][count(. | //*[@for = 'u_0_0']) = count(//*[@for = 'u_0_0'])][count(. | id(&quot;loginbutton&quot;)) = count(id(&quot;loginbutton&quot;))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;loginbutton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiButton uiButtonConfirm uiButtonLarge</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginbutton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>u_0_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginbutton&quot;)</value>
   </webElementProperties>
</WebElementEntity>
