<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>c113df9c-9108-4c30-9b1d-273de9e401a2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://oddlefacebooklogindomain.staging.oddle.co/en_SG/facebook/149784952181218/signup</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[3]/div[3]/div[@class=&quot;wuzp1o-0 cCUvkJ&quot;]/div[@class=&quot;wuzp1o-2 gfSaCZ&quot;]/div[@class=&quot;wuzp1o-5 eezkNJ&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 ghApmL&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/div[@class=&quot;qxyyek-0 gDhhcJ e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/div[@class=&quot;sc-bRBYWo cdRCbH e9phw6-0 jBJmyp&quot;]/form[1]/div[@class=&quot;s5csc7v-1 gBEfBY&quot;]/iframe[1]</value>
   </webElementProperties>
</WebElementEntity>
