<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lastName</name>
   <tag></tag>
   <elementGuidId>f00abae3-e6f0-46e3-9ddb-922b169dc68d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dot6ul-3 hwnBiq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^((?![\d~`!@#\$%\^&amp;\*\(\)_=\+\[\]\{\}\\|:;&quot;&lt;>/?]).){1,255}$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[3]/div[3]/div[@class=&quot;wuzp1o-0 cCUvkJ&quot;]/div[@class=&quot;wuzp1o-2 gfSaCZ&quot;]/div[@class=&quot;wuzp1o-5 eezkNJ&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 ghApmL&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/div[@class=&quot;qxyyek-0 gDhhcJ e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 jBJmyp&quot;]/div[@class=&quot;sc-bRBYWo cdRCbH e9phw6-0 jBJmyp&quot;]/form[1]/div[@class=&quot;s1kn4au3-0 gYDZag&quot;]/div[3]/div[@class=&quot;dot6ul-0 hXxpax&quot;]/div[@class=&quot;dot6ul-1 cVPFlx&quot;]/input[@class=&quot;dot6ul-3 hwnBiq&quot;]</value>
   </webElementProperties>
</WebElementEntity>
