<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_login to set delivery-XPATH</name>
   <tag></tag>
   <elementGuidId>c5cc5566-c3b1-4428-b497-750d7fe9a245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/div/div/div/div[3]/div[3]/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[1]/form/div[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s3mrp9-1-sc-Rmtcm gMmdOy s3mrp9-0-div eyJZCt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/div/div/div/div[3]/div[3]/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[1]/form/div[2]/a/div</value>
   </webElementProperties>
</WebElementEntity>
