<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_deliveryAddressOne</name>
   <tag></tag>
   <elementGuidId>5bf27fff-942b-419d-9676-5fcb7c9865c1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dot6ul-3 hrTYle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deliveryAddressOne</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>71 Ayer Rajah Crescent``</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[@class=&quot;s111nt22-0 isjfum&quot;]/div[3]/div[3]/div[@class=&quot;wuzp1o-0 cCUvkJ&quot;]/div[@class=&quot;wuzp1o-2 gfSaCZ&quot;]/div[@class=&quot;wuzp1o-5 eezkNJ&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 bScUdW&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/div[@class=&quot;e9phw6-1-sc-bdVaJa cjHrgj e9phw6-0 acCCi&quot;]/div[@class=&quot;e9phw6-0-sc-chPdSV cCpcRM&quot;]/div[@class=&quot;eslncg-2 bKwwBK&quot;]/div[@class=&quot;eslncg-3 iNeBZk&quot;]/div[@class=&quot;eslncg-4 gugdEn&quot;]/form[1]/div[@class=&quot;sc-iAyFgw kSIHfH e9phw6-0 jBJmyp&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;dot6ul-0 fZRZGp&quot;]/div[@class=&quot;dot6ul-1 cVPFlx&quot;]/input[@class=&quot;dot6ul-3 hrTYle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
